import { describe, expect, test } from "bun:test"

import {
  createResponsesStreamState,
  translateResponsesStreamEvent,
} from "~/routes/messages/responses-stream-translation"

describe("Responses API to Anthropic Streaming Translation", () => {
  test("should handle response.created event", () => {
    const state = createResponsesStreamState()

    const event = {
      type: "response.created",
      response: {
        id: "resp_abc123",
        object: "response",
        created_at: 1234567890,
        model: "gpt-5-codex",
        output: [],
        output_text: "",
        status: "in_progress",
        usage: {
          input_tokens: 10,
          output_tokens: 0,
          total_tokens: 10,
        },
        error: null,
        incomplete_details: null,
        instructions: null,
        metadata: null,
        parallel_tool_calls: false,
        temperature: null,
        tool_choice: null,
        tools: [],
        top_p: null,
      },
      sequence_number: 0,
    }

    const anthropicEvents = translateResponsesStreamEvent(event, state)

    expect(anthropicEvents).toHaveLength(1)
    expect(anthropicEvents[0]?.type).toBe("message_start")
    expect(state.messageStartSent).toBe(true)
  })

  test("should handle text delta events", () => {
    const state = createResponsesStreamState()
    state.messageStartSent = true

    // For text messages, output_item.added only returns message_start if needed
    // The content_block_start is generated by output_text.delta when first text arrives
    const deltaEvent = {
      type: "response.output_text.delta",
      output_index: 0,
      content_index: 0,
      delta: "Hello",
      sequence_number: 2,
    }

    const deltaEvents = translateResponsesStreamEvent(deltaEvent, state)

    // Should contain content_block_start followed by content_block_delta
    expect(deltaEvents.length).toBeGreaterThanOrEqual(1)

    const hasBlockStart = deltaEvents.some(
      (e) => e.type === "content_block_start",
    )
    const hasBlockDelta = deltaEvents.some(
      (e) => e.type === "content_block_delta",
    )

    expect(hasBlockStart).toBe(true)
    expect(hasBlockDelta).toBe(true)

    const deltaEvent2 = deltaEvents.find(
      (e) => e.type === "content_block_delta",
    )
    if (deltaEvent2?.type === "content_block_delta") {
      expect(deltaEvent2.delta.type).toBe("text_delta")
      if (deltaEvent2.delta.type === "text_delta") {
        expect(deltaEvent2.delta.text).toBe("Hello")
      }
    }
  })

  test("should handle function call with arguments delta", () => {
    const state = createResponsesStreamState()
    state.messageStartSent = true

    const addedEvent = {
      type: "response.output_item.added",
      output_index: 0,
      item: {
        type: "function_call",
        id: "call_1",
        role: "assistant",
        name: "TodoWrite",
        arguments: "",
        status: "in_progress",
      },
      sequence_number: 1,
    }

    const addedEvents = translateResponsesStreamEvent(addedEvent, state)
    expect(addedEvents[0]?.type).toBe("content_block_start")
    if (addedEvents[0]?.type === "content_block_start") {
      expect(addedEvents[0].content_block.type).toBe("tool_use")
    }

    const argsPartial = '{"todos":[{"content":"'
    const deltaEvent = {
      type: "response.function_call_arguments.delta",
      output_index: 0,
      item_id: "call_1",
      delta: argsPartial,
      sequence_number: 2,
    }

    const deltaEvents = translateResponsesStreamEvent(deltaEvent, state)

    expect(deltaEvents).toHaveLength(1)
    expect(deltaEvents[0]?.type).toBe("content_block_delta")
    if (deltaEvents[0]?.type === "content_block_delta") {
      expect(deltaEvents[0].delta.type).toBe("input_json_delta")
      if (deltaEvents[0].delta.type === "input_json_delta") {
        expect(deltaEvents[0].delta.partial_json).toBe(argsPartial)
      }
    }
  })

  test("should handle response.completed event", () => {
    const state = createResponsesStreamState()
    state.messageStartSent = true
    state.nextContentBlockIndex = 1

    const completedEvent = {
      type: "response.completed",
      response: {
        id: "resp_abc123",
        object: "response",
        created_at: 1234567890,
        model: "gpt-5-codex",
        output: [
          {
            type: "message",
            id: "msg_1",
            role: "assistant",
            content: [
              {
                type: "text",
                text: "Hello!",
              },
            ],
            status: "completed",
          },
        ],
        output_text: "Hello!",
        status: "completed",
        usage: {
          input_tokens: 10,
          output_tokens: 5,
          total_tokens: 15,
        },
        error: null,
        incomplete_details: null,
        instructions: null,
        metadata: null,
        parallel_tool_calls: false,
        temperature: null,
        tool_choice: null,
        tools: [],
        top_p: null,
      },
      sequence_number: 10,
    }

    const events = translateResponsesStreamEvent(completedEvent, state)

    expect(state.messageCompleted).toBe(true)
    const hasMessageDelta = events.some((e) => e.type === "message_delta")
    const hasMessageStop = events.some((e) => e.type === "message_stop")

    expect(hasMessageDelta).toBe(true)
    expect(hasMessageStop).toBe(true)
  })

  test("should handle response.failed event", () => {
    const state = createResponsesStreamState()
    state.messageStartSent = true

    const failedEvent = {
      type: "response.failed",
      response: {
        id: "resp_failed",
        object: "response",
        created_at: 1234567890,
        model: "gpt-5-codex",
        output: [],
        output_text: "",
        status: "failed",
        usage: null,
        error: {
          message: "Model overloaded",
        },
        incomplete_details: null,
        instructions: null,
        metadata: null,
        parallel_tool_calls: false,
        temperature: null,
        tool_choice: null,
        tools: [],
        top_p: null,
      },
      sequence_number: 5,
    }

    const events = translateResponsesStreamEvent(failedEvent, state)

    expect(state.messageCompleted).toBe(true)
    const hasError = events.some((e) => e.type === "error")
    expect(hasError).toBe(true)

    const errorEvent = events.find((e) => e.type === "error")
    if (errorEvent) {
      expect(errorEvent.error.message).toContain("failed")
    }
  })

  test("should handle error event", () => {
    const state = createResponsesStreamState()

    const errorEvent = {
      type: "error",
      code: "server_error",
      message: "Internal server error occurred",
      param: null,
      sequence_number: 1,
    }

    const events = translateResponsesStreamEvent(errorEvent, state)

    expect(state.messageCompleted).toBe(true)
    expect(events).toHaveLength(1)
    expect(events[0]?.type).toBe("error")
    if (events[0]?.type === "error") {
      expect(events[0].error.message).toBe("Internal server error occurred")
    }
  })
})
